dmBehaviors:
  dmQuickSandBehavior:
    section: Media Gallery
    name: QuickSand
    form: dmQuickSandBehaviorForm
    view: dmQuickSandBehaviorView
  dmQuickSandMetadataBehavior:
    section: Metadata
    name: QuickSand Metadata
    form: dmQuickSandMetadataBehaviorForm
    view: dmQuickSandMetadataBehaviorView